# Generated by Django 5.0.6 on 2026-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_emoji_profile_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='codigo_inscripcion',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
