# Generated by Django 5.0.6 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='estado',
            field=models.CharField(choices=[('borrador', '📝 Borrador'), ('publicado', '✅ Publicado')], default='borrador', max_length=20),
        ),
    ]
