# Generated by Django 5.0.6 on 2026-05-28 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coursematerial_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='materiales_cursos/')),
                ('estado', models.CharField(choices=[('borrador', '📝 Borrador'), ('publicado', '✅ Publicado')], default='borrador', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.course')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
