# Generated by Django 5.0.6 on 2026-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_material_delete_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=20),
        ),
    ]
