# Generated by Django 5.0.6 on 2026-05-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador'), ('teacher', 'Profesor'), ('student', 'Estudiante')], max_length=20),
        ),
    ]
