# Generated by Django 5.0.6 on 2026-05-29 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile')),
                ('numero_empleado', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grado_academico',
            field=models.CharField(default='No especificado', max_length=50),
        ),
    ]
